FROM  python:3
LABEL "maintainer"="{{ cookiecutter.author_name }}"
LABEL "version"="{{ cookiecutter.version }}"
LABEL "description"="{{ cookiecutter.description }}"
LABEL "license"="{{ cookiecutter.open_source_license }}"

# TO DO: add requirements dependencies
